language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-22

install: gradle clean build --info
#script: gradle check jacocoTestReport --stacktrace --info --continue
#after_success: gradle coveralls --info